---
version: 2
registries:
  github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/dysnomia-studio/index.json
    username: ${{ secrets.GHP_USER }}
    password: ${{ secrets.GHP_TOKEN }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "monthly"