name: Docker

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dysnomia-studio/dehash-me

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Set env.DOCKER_TAG / env.DOCKER_IMAGE_PUSH
        run:
          if [[ "${{ startsWith(github.event.ref, 'refs/tags/') }}" == "true" ]]; then
            echo "DOCKER_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV;
            echo "DOCKER_IMAGE_PUSH=true"  >> $GITHUB_ENV;
          else
            echo "DOCKER_TAG=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:temp" >> $GITHUB_ENV;
            echo "DOCKER_IMAGE_PUSH=false"  >> $GITHUB_ENV;
          fi

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445
        with:
          context: .
          push: ${{ env.DOCKER_IMAGE_PUSH }}
          tags: ${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GITHUB_BRANCH=${{ env.BRANCH }}
            GHP_TOKEN=${{ secrets.GHP_TOKEN }}
            GHP_USER=${{ secrets.GHP_USER }}
            SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}
            SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
            
  deploy_app:
    needs: build
    if: startsWith(github.event.ref, 'refs/tags/')

    runs-on: ubuntu-latest
    steps:
      - name: Update infra
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.UPDATE_INFRA_TOKEN }}
          repository: Dysnomia-studio/argocd-infra
          event-type: update-infra